apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /orgs$1$2/$3
spec:
  rules:
    - host: myapp.com
      http:
        paths:
          - path: /orgs(/|$)(.*)/(comments)
            pathType: Prefix
            backend:
              service:
                name: comment-service
                port:
                  number: 3334
          - path: /orgs(/|$)(.*)/(members)
            pathType: Prefix
            backend:
              service:
                name: member-service
                port:
                  number: 3991