apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-deployment
  labels:
    app: deployment
spec:
  rules:
    - host: nginx.mustain.local
      http:
        paths:
          - path: /members
            backend:
              serviceName: members-service
              servicePort: 3333
          - path: /comments
            backend:
              serviceName: comment-service
              servicePort: 3334